services:
  product-service:
    build: .
    container_name: product-service
    ports:
      - "5002:5002"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - ../food-common-package:/food-common-package
    command: sh -c "npm install && npm install /food-common-package && npx prisma migrate deploy && npm run dev"
    depends_on:
      - product-db
    networks:
      - product-network

  product-db:
    image: postgres:16
    container_name: product-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: food_product_db
    ports:
      - "5434:5432"
    volumes:
      - product_db_data:/var/lib/postgresql/data
    networks:
      - product-network

volumes:
  product_db_data:

networks:
  product-network:
    external: true
    name: food-auth-service_default
